### ISSUE TITLE
Chat messages not restored on refresh

### ISSUE THREAD

**Issue by axelboc** [mxcube/mxcube3#1361]
`GET /remoteaccess/chat` throws a silent error like in #1355, so the messages aren't retrieved.

```
Traceback (most recent call last):
  File "/home/bocciare/tools/micromamba/envs/mxcubeweb/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request rv = self.dispatch_request()
  File "/home/bocciare/tools/micromamba/envs/mxcubeweb/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
  File "/home/bocciare/tools/micromamba/envs/mxcubeweb/lib/python3.10/site-packages/flask_security/decorators.py", line 432, in decorated_view return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/home/bocciare/workspace/mxcubeweb/mxcubeweb/routes/ra.py", line 215, in get_all_mesages return jsonify({"messages": app.chat.get_all_messages()})
  File "/home/bocciare/workspace/mxcubeweb/mxcubeweb/core/components/chat.py", line 40, in get_all_messages "username": _m.username,

AttributeError: 'Message' object has no attribute 'username' 
```

**Comment by marcus-oscarsson** [comment]
Hm, I think I fixed that I while back, or maybe this is new error of the same type. Have to double check.

**Comment by axelboc** [comment]
Can't reproduce this morning. :thinking: Maybe my local database was corrupted.

**Comment by axelboc** [comment]
Ah yes, one has to have messages to restore. If no messages were sent before refreshing, the response is correct: `{ "messages": [] }`

**Comment by marcus-oscarsson** [comment]
:), I have a local fix for this that I have not made a PR for yet. I'm not super happy with as it is but Ill make a draft PR
