### ISSUE TITLE
'NoneType' object has no attribute '_set_loaded' error when unmounting a sample

### ISSUE THREAD

**Issue by elmjag** [mxcube/mxcube3#1363]
When running with mocked beamline, you get the error below after clicking the 'Unmount' button.

![image](https://github.com/user-attachments/assets/d71b4f8e-3974-4b67-9e77-63abc64ce9e6)

In the log, there is this error:

```
2024-08-23 08:40:30,137 |MX3.HWR|ERROR  | [SC] sample could not be mounted
Traceback (most recent call last):
  File "/home/elmjag/mxcube/web/mxcubeweb/core/components/samplechanger.py", line 273, in unmount_sample_clean_up
    HWR.beamline.sample_changer.unload(sample["location"], wait=False)
  File "/home/elmjag/mxcube/core/mxcubecore/HardwareObjects/mockup/SampleChangerMockup.py", line 92, in unload
    sample._set_loaded(False, True)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_set_loaded'
```

How to reproduce:

- goto `Queued Samples` tab
- click `Create new sample` button
- write sample name and protein acronym, click `Mount`
- click `Unmount` button

**Comment by marcus-oscarsson** [comment]
I noticed that too, I have a fix for it :)
