### ISSUE TITLE
UI hangs on loading screen after login when using latest mxcubecore (v1.142.0)

### ISSUE THREAD

**Issue by elmjag** [mxcube/mxcube3#1372]
When using latest mxcubeweb with latest mxcubecore (v1.142.0), the UI get's stuck on loading screen after login.

Following error are visible in the JavaScript console:

![image](https://github.com/user-attachments/assets/d20f9cfe-0a92-4d55-a222-e12a8ed50027)

**Comment by marcus-oscarsson** [comment]
I might have a fix for it

**Comment by beteva** [comment]
I guess it is linked to the new beam handling.

**Comment by elmjag** [comment]
> I guess it is linked to the new beam handling.

Not necessary, it seems that it fails doing request to `mxcube/api/v0.1/sampleview/camera`

The backend replies with a traceback, like this:

```
Traceback (most recent call last):
  File "/opt/mamba/envs/mxcube/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mamba/envs/mxcube/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mamba/envs/mxcube/lib/python3.11/site-packages/flask_security/decorators.py", line 429, in decorated_view
    return current_app.ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elmjag/mxcube/web/mxcubeweb/routes/samplecentring.py", line 67, in get_image_data
    data = app.beamline.get_viewport_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elmjag/mxcube/web/mxcubeweb/core/components/beamline.py", line 112, in get_viewport_info
    video_sizes = HWR.beamline.sample_view.camera.get_available_stream_sizes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_available_stream_sizes'
```

**Comment by marcus-oscarsson** [comment]
Solved by https://github.com/mxcube/mxcubecore/pull/1000
