### ISSUE TITLE
 Python 3.8 incompatible typehints in components/harvester.py

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#1414]
@woutdenolf noticed that the there are some Python 3.8 incompatible type-hints used.

Originally reported in issue #1383 

```
mxcubeweb-server -r $(pwd)/mxcubeweb/demo/ --static-folder $(pwd)/mxcubeweb/ui/build/ -L debug

Traceback (most recent call last):
  File "/home/denolf/.local/wdnbashutils/virtualenvs/mxcubeweb/bin/mxcubeweb-server", line 3, in <module>
    from mxcubeweb import main
  File "/home/denolf/projects/sb/mxcubeweb/mxcubeweb/__init__.py", line 14, in <module>
    from mxcubeweb.app import MXCUBEApplication as mxcube  # noqa: E402
  File "/home/denolf/projects/sb/mxcubeweb/mxcubeweb/app.py", line 36, in <module>
    from mxcubeweb.core.components.harvester import Harvester
  File "/home/denolf/projects/sb/mxcubeweb/mxcubeweb/core/components/harvester.py", line 14, in <module>
    class Harvester(ComponentBase):
  File "/home/denolf/projects/sb/mxcubeweb/mxcubeweb/core/components/harvester.py", line 189, in Harvester
    def get_sample_info(self, sampleID: str) -> dict[str]:
TypeError: 'type' object is not subscriptable
```

**Comment by marcus-oscarsson** [comment]
Can be solved but using `from __future__ import annotations` or `from typing import Dict`

**Comment by marcus-oscarsson** [comment]
Perhaps @jbflo can have a look when he is back :) ?

**Comment by marcus-oscarsson** [comment]
:), I'm wondering if this however is a development that we only have on our internal GitLab. @woutdenolf, you checked out the GitLab code right. Because the GitHub test action should have caught this issue, however we are not testing against Python 3.8 on GitLab ?

**Comment by marcus-oscarsson** [comment]
Actually just double checking and the code is pretty much identical, so this line is the same here on GitHub: 

https://github.com/mxcube/mxcubeweb/blob/4ce5472fd5a6ebb587fc87d382c16466c52fdef3/mxcubeweb/core/components/harvester.py#L189

So its strange that this passes the tests, or am I overlooking something ?

**Comment by jbflo** [comment]
did not have **python 3.8 en in place**
just Setup a python 3.8 env and had the issue that @woutdenolf raised.

**Comment by marcus-oscarsson** [comment]
Yes, I found the issue. I'm not sure how this was meant to work:

https://github.com/mxcube/mxcubeweb/blob/4ce5472fd5a6ebb587fc87d382c16466c52fdef3/.github/workflows/build_and_test.yml#L48

As far as I can see this never uses the interpreter specified in the matrix : 

https://github.com/mxcube/mxcubeweb/blob/4ce5472fd5a6ebb587fc87d382c16466c52fdef3/.github/workflows/build_and_test.yml#L15

I guess we could perhaps add something here:

https://github.com/mxcube/mxcubeweb/blob/4ce5472fd5a6ebb587fc87d382c16466c52fdef3/.github/workflows/build_and_test.yml#L46

**Comment by marcus-oscarsson** [comment]
@jbflo, thanks If you run `pytest` the tests are still failing because there is the same issue in `mxcubecore`. Do you think you can make a PR for mxcubecore as well

**Comment by jbflo** [comment]
> @jbflo, thanks If you run `pytest` the tests are still failing because there is the same issue in `mxcubecore`. Do you think you can make a PR for mxcubecore as well

yes, i did it as well https://github.com/mxcube/mxcubecore/pull/1031

**Comment by marcus-oscarsson** [comment]
Oh, yes I got lost in the issue "cross-over" Thanks alot @jbflo  :+1:
