### ISSUE TITLE
trouble with python dependencies during installation

### ISSUE THREAD

**Issue by dsclassen** [mxcube/mxcube3#791]
I'm attempting an install on a CentOS 7.5 machine with default system python 2.7.5

I've installed all system dependencies and started the redis server.

then install the python dependencies:

```
[root@test-machine mxcube3]# pip install -r requirements.txt 
Collecting gevent==1.2.2 (from -r requirements.txt (line 1))
Requirement already satisfied: flask==0.12.2 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 2)) (0.12.2)
Requirement already satisfied: flask-socketio==2.9.2 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 3)) (2.9.2)
Requirement already satisfied: gevent-websocket==0.10.1 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (0.10.1)
Requirement already satisfied: Flask-Session==0.3.1 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (0.3.1)
Requirement already satisfied: python-socketio==1.8.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 6)) (1.8.0)
Requirement already satisfied: louie in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 7)) (1.1)
Requirement already satisfied: redis in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 8)) (2.10.6)
Requirement already satisfied: scipy in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 9)) (1.1.0)
Requirement already satisfied: mock in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 10)) (2.0.0)
Requirement already satisfied: pbr in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 11)) (4.2.0)
Requirement already satisfied: funcsigs in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 12)) (1.0.2)
Requirement already satisfied: jsonpickle in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 13)) (0.9.6)
Requirement already satisfied: pillow in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 14)) (5.2.0)
Requirement already satisfied: suds in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 15)) (0.4)
Requirement already satisfied: python-ldap in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 16)) (3.1.0)
Requirement already satisfied: lxml in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 17)) (4.2.3)
Requirement already satisfied: numpy in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 18)) (1.15.0)
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 19)) (2.19.1)
Requirement already satisfied: v4l2 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 20)) (0.2)
Requirement already satisfied: scandir in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 21)) (1.7)
Requirement already satisfied: greenlet>=0.4.10 in /usr/lib64/python2.7/site-packages (from gevent==1.2.2->-r requirements.txt (line 1)) (0.4.14)
Requirement already satisfied: itsdangerous>=0.21 in /usr/lib/python2.7/site-packages (from flask==0.12.2->-r requirements.txt (line 2)) (0.24)
Requirement already satisfied: click>=2.0 in /usr/lib/python2.7/site-packages (from flask==0.12.2->-r requirements.txt (line 2)) (6.7)
Requirement already satisfied: Jinja2>=2.4 in /usr/lib/python2.7/site-packages (from flask==0.12.2->-r requirements.txt (line 2)) (2.10)
Requirement already satisfied: Werkzeug>=0.7 in /usr/lib64/python2.7/site-packages (from flask==0.12.2->-r requirements.txt (line 2)) (0.14.1)
Requirement already satisfied: python-engineio>=1.2.1 in /usr/lib/python2.7/site-packages (from python-socketio==1.8.0->-r requirements.txt (line 6)) (2.2.0)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python2.7/site-packages (from python-socketio==1.8.0->-r requirements.txt (line 6)) (1.11.0)
Requirement already satisfied: nose>=0.8.3 in /usr/lib/python2.7/site-packages (from louie->-r requirements.txt (line 7)) (1.3.7)
Requirement already satisfied: pyasn1>=0.3.7 in /usr/lib/python2.7/site-packages (from python-ldap->-r requirements.txt (line 16)) (0.4.4)
Requirement already satisfied: pyasn1-modules>=0.1.5 in /usr/lib/python2.7/site-packages (from python-ldap->-r requirements.txt (line 16)) (0.2.2)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python2.7/site-packages (from requests->-r requirements.txt (line 19)) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests->-r requirements.txt (line 19)) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests->-r requirements.txt (line 19)) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests->-r requirements.txt (line 19)) (2018.4.16)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib64/python2.7/site-packages (from Jinja2>=2.4->flask==0.12.2->-r requirements.txt (line 2)) (1.0)
Installing collected packages: gevent
  Found existing installation: gevent 1.3.5
    Uninstalling gevent-1.3.5:
      Successfully uninstalled gevent-1.3.5
Successfully installed gevent-1.2.2
```

I've tried a few different version of gevent, but none of them support successful start of the mxcube3-server.

```
[root@test-machine mxcube3]# python mxcube3-server -r test/HardwareObjectsMockup.xml
Traceback (most recent call last):
  File "mxcube3-server", line 2, in <module>
    from gevent import monkey
  File "/usr/lib64/python2.7/site-packages/gevent/__init__.py", line 51, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 31, in <module>
    from gevent._util import _NONE
ImportError: cannot import name _NONE
```

Clearly there is some problem with gevent. Does anyone have an idea of how to fix this?

Thanks

**Comment by dsclassen** [comment]
OK. I have temporarily fixed this by uninstalling the system gevent and the pip-installed gevent and then reinstalling ONLY the python-gevent available from the centos extras repo (version 1.0).

**Comment by mguijarr** [comment]
I recommend installing mxcube 3 with Conda ; it lets you having separated Python environments, it is quite handy compared to relying on system Python. Even without Conda, using virtual environments is also a good idea.

**Comment by marcus-oscarsson** [comment]
Hi @dsclassen 

How did it go with the installation ?, please let us know if there is anything we can do to help you out. We can also arrange for a remote demo if you are interested. You can reach me at oscarsso@esrf.fr if you prefer to continue the discussion over mail.

Regards,
Marcus
